---
- hosts: all
  vars:
    maven_version: "3.6.0"
    atom_version: "1.26.1"
    yq_linux_version: "1.14.0"
    terraform_version: "0.11.10"
    postman_version: "6.5.2"
    fly_version: "3.14.1"
    lastpass_version: "1.3.1"
    docker_users:
      - vagrant
  gather_facts: yes
  become: yes
  roles:
    - git
    - maven
    - desktop
